### ISSUE TITLE
Per-document topic distribution (ATM)?

### ISSUE THREAD

**Issue by mikekestemont** [arongdari/python-topic-model#6]
Thanks for a great package -- I just got the author-topic model successfully running and I was wondering whether there is a simple way to get the per-document topic distribution for (a) the documents an author-topic model was fitted on or (b) new documents. Thanks in advance for any replies!

**Comment by dongwookim-ml** [comment]
Hi, the author-topic model does not provide any information about topic distribution per document.
The model assumes that a document is generated by the average topic distribution of authors (each author has equal contribution to the document), so you could use it as a topic distribution of a new document (if you know the authors of the document already).
